---
- name: Default Playbook
  hosts: default
  become: true

  tasks:
    - name: Install Packages
      apt:
        name: "{{item}}"
        update_cache: yes
        state: present
      loop: "{{ packages.split(',') }}"
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

